// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zztqwjstrqmwpmcqfiqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dHF3anN0cnFtd3BtY3FmaXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTQzNTUsImV4cCI6MjA2MzI5MDM1NX0.lm1jXxQuvWu3nSJlbQWfWBpVkVUDnCesyuZ0y6DwBJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);